AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: React Client-Side Rendered Application

Parameters:
  CertificateARN:
    Description: ACM certificate ARN
    Type: String
    Default: arn:aws:acm:us-east-1:254161167246:certificate/10791c4f-3dae-4627-b3df-a5e353bd6be5
  WebACLARN:
    Description: Web ACL ARN
    Type: String
    Default: arn:aws:wafv2:us-east-1:254161167246:global/webacl/Restricted-Countries/e19c8c41-bc6a-45bf-99c9-166c95ef5e93
  S3BucketName:
    Description: S3 bucket name
    Type: String
    Default: hf-cde-cc-frontend-dev
  CNAME:
    Description: CloudFront CNAME 
    Type: String
    Default: customer-centr-frontend-dev.healthfirst.org
  # AwsContentSecurityPolicy:
  #   Description: AWS ContentSecurityPolicy
  #   Type: String 
 
Resources:
##########################################################################
### CLOUDFRONT / ORIGIN ACCESS CONTROL ##################################
##########################################################################
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Name: !Join
          - ""
          - - "access-identity-"
            - !Ref S3BucketName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
##########################################################################
### CLOUDFRONT / DISTRIBUTION ############################################
##########################################################################
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Join [ ., [ !Ref S3BucketName, s3.amazonaws.com ] ]
          Id: !Join [ -, [ S3, !Ref S3BucketName ] ]
          S3OriginConfig: 
            OriginAccessIdentity: ''
          OriginAccessControlId: !GetAtt OAC.Id
        Enabled: true
        Comment: !Join [ -, [ S3, !Ref S3BucketName ] ]
        Logging: 
          Bucket: !Join [ ., [ !Ref S3BucketName, s3.amazonaws.com ] ]
          Prefix: uilogs
          IncludeCookies: false
        PriceClass: PriceClass_100
        HttpVersion: http1.1
        Aliases: 
          - !Ref CNAME
        DefaultRootObject: index.html
        DefaultCacheBehavior: 
          TargetOriginId: !Join [ -, [ S3, !Ref S3BucketName ] ]
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          ForwardedValues: 
              QueryString: false
              Cookies:
                Forward: none
          SmoothStreaming : false
          Compress: false
          ## Commenting this currently until we get an update from DEVOPS
          CustomHeaders:
            HeaderName: Content-Security-Policy
            HeaderValue:  "default-src 'self' 'unsafe-eval' healthfirst.org *.healthfirst.org *.google.com *.googletagmanager.com *.googleapis.com *.google-analytics.com *.typekit.net *.fontawesome.com *.gstatic.com *.cvshealth.com *.davisvision.com *.teladoc.com cdn.segment.com api.segment.io *.twilio.com siteintercept.qualtrics.com *.siteintercept.qualtrics.com; frame-src player.vimeo.com www.google.com identity-dev.healthfirst.org; frame-ancestors 'self'; object-src 'none'; img-src 'self' healthfirst.org *.healthfirst.org *.google-analytics.com maps.gstatic.com maps.googleapis.com *.typekit.net data: i.vimeocdn.com vimeocdn.com siteintercept.qualtrics.com; connect-src 'self' *.google-analytics.com *.healthfirst.org api.segment.io cdn.segment.com siteintercept.qualtrics.com maps.googleapis.com hf-cde-enterprise-customer-eapi-dev.us-e1.cloudhub.io wss://*.twilio.com *.oktapreview.com *.okta.com *.split.io *.execute-api.us-east-1.amazonaws.com hf-cde-preference-center-react-eapi-dev.us-e1.cloudhub.io"
        # The certificate to use when viewers use HTTPS to request objects.
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
          AcmCertificateArn: !Ref CertificateARN
        WebACLId: !Ref WebACLARN
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
