AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: React Client-Side Rendered Application

Parameters:
  CertificateARN:
    Description: ACM certificate ARN
    Type: String
    Default: arn:aws:acm:us-east-1:254161167246:certificate/10791c4f-3dae-4627-b3df-a5e353bd6be5
  WebACLARN:
    Description: Web ACL ARN
    Type: String
    Default: arn:aws:wafv2:us-east-1:254161167246:global/webacl/Restricted-Countries/e19c8c41-bc6a-45bf-99c9-166c95ef5e93
  S3BucketName:
    Description: S3 bucket name
    Type: String
    Default: hf-cde-cc-frontend-dev
  OriginAccessIdentity:
    Description: OAI 
    Type: String
    Default: origin-access-identity/cloudfront/E4DT39JQHX44S
  CNAME:
    Description: CloudFront CNAME 
    Type: String
    Default: customer-centr-frontend-dev.healthfirst.org
 
Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Join [ ., [ !Ref S3BucketName, s3.amazonaws.com ] ]
          Id: !Join [ -, [ S3, !Ref S3BucketName ] ]
          S3OriginConfig: 
            OriginAccessIdentity: !Ref OriginAccessIdentity
        Enabled: true
        Comment: !Join [ -, [ S3, !Ref S3BucketName ] ]
        Logging: 
          Bucket: !Join [ ., [ !Ref S3BucketName, s3.amazonaws.com ] ]
          Prefix: uilogs
          IncludeCookies: false
        PriceClass: PriceClass_100
        HttpVersion: http1.1
        Aliases: 
          - !Ref CNAME
        DefaultRootObject: index.html
        DefaultCacheBehavior: 
          TargetOriginId: !Join [ -, [ S3, !Ref S3BucketName ] ]
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          ForwardedValues: 
              QueryString: false
              Cookies:
                Forward: none
          SmoothStreaming : false
          Compress: false
          CustomHeaders:
            - HeaderName: Content-Security-Policy
              HeaderValue: report-uri /api/csp/report;script-src 'self' healthfirsthere.mpeasylink.com healthfirst.org *.healthfirst.org *.google.com *.googletagmanager.com *.googleapis.com *.google-analytics.com *.typekit.net *.fontawesome.com *.gstatic.com *.okta.com *.oktapreview.com *.healthx.com *.myhfny.org *.cvshealth.com *.davisvision.com *.teladoc.com *.callidusinsurance.net *.hfgroupenroll.org *.myhfgroup.org *.convertlanguage.com cdnjs.cloudflare.com cdn.segment.com api.segment.io *.twilio.com siteintercept.qualtrics.com *.siteintercept.qualtrics.com 'nonce-OGG5QrZValOHUUlE3Z9crfOl7N9hd13u';script-src-elem 'self' healthfirsthere.mpeasylink.com healthfirst.org *.healthfirst.org *.google.com *.googletagmanager.com *.googleapis.com *.google-analytics.com *.typekit.net *.fontawesome.com *.gstatic.com *.okta.com *.oktapreview.com *.healthx.com *.myhfny.org *.cvshealth.com *.davisvision.com *.teladoc.com *.callidusinsurance.net *.hfgroupenroll.org *.myhfgroup.org *.convertlanguage.com cdnjs.cloudflare.com cdn.segment.com api.segment.io *.twilio.com 'nonce-OGG5QrZValOHUUlE3Z9crfOl7N9hd13u';style-src 'self' healthfirsthere.mpeasylink.com healthfirst.org *.healthfirst.org *.google.com *.googletagmanager.com *.googleapis.com *.google-analytics.com *.typekit.net *.fontawesome.com *.gstatic.com *.okta.com *.oktapreview.com *.healthx.com *.myhfny.org *.cvshealth.com *.davisvision.com *.teladoc.com *.callidusinsurance.net *.hfgroupenroll.org *.myhfgroup.org *.convertlanguage.com cdnjs.cloudflare.com cdn.segment.com api.segment.io *.twilio.com use.typekit.net 'nonce-OGG5QrZValOHUUlE3Z9crfOl7N9hd13u';style-src-elem 'self' use.typekit.net;frame-src player.vimeo.com www.google.com;object-src 'none';img-src 'self' healthfirst.org *.healthfirst.org *.google-analytics.com maps.gstatic.com maps.googleapis.com *.typekit.net i.vimeocdn.com vimeocdn.com siteintercept.qualtrics.com;connect-src 'self' *.google-analytics.com *.healthfirst.org api.segment.io cdn.segment.com siteintercept.qualtrics.com maps.googleapis.com wss://*.twilio.com *.oktapreview.com *.okta.com *.split.io *.execute-api.us-east-1.amazonaws.com hf-dpc-tic-customer-details-eapi-dev.us-e1.cloudhub.io hf-dpc-tic-negotiatedrates-eapi-dev.us-e1.cloudhub.io hf-cde-enterprise-customer-eapi-dev.us-e1.cloudhub.io hf-dpc-tic-shoppable-service-eapi-dev.us-e1.cloudhub.io hf-cde-preference-center-react-eapi-dev.us-e1.cloudhub.io;style-src-attr 'nonce-OGG5QrZValOHUUlE3Z9crfOl7N9hd13u'
        ## The certificate to use when viewers use HTTPS to request objects.
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
          AcmCertificateArn: !Ref CertificateARN
        WebACLId: !Ref WebACLARN
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

