export const REQUEST_CLAIM_LIST = "REQUEST_CLAIM_LIST";
export const RECEIVE_CLAIM_LIST = "RECEIVE_CLAIM_LIST";

export const REQUEST_CLAIM_DETAILS = "REQUEST_CLAIM_DETAILS";
export const RECEIVE_CLAIM_DETAILS = "RECEIVE_CLAIM_DETAILS";

export const REQUEST_CLAIMS_EOB = "REQUEST_CLAIM_EOB";
export const RECEIVE_CLAIMS_EOB = "RECEIVE_CLAIM_EOB";

export const REQUEST_AUTHORIZATION_LIST = "REQUEST_AUTHORIZATION_LIST";
export const RECEIVE_AUTHORIZATION_LIST = "RECEIVE_AUTHORIZATION_LIST";

export const REQUEST_AUTHORIZATION_DETAILS = "REQUEST_AUTHORIZATION_DETAILS";
export const RECEIVE_AUTHORIZATION_DETAILS = "RECEIVE_AUTHORIZATION_DETAILS";

export const SET_TAB_VALUE = "SET_TAB_VALUE";

export const REQUEST_CUSTOMER_OOP = "REQUEST_CUSTOMER_OOP";
export const RECEIVE_CUSTOMER_OOP = "RECEIVE_CUSTOMER_OOP";

export const REQUEST_NEXT_QUESTION = "REQUEST_NEXT_QUESTION";
export const REQUEST_PREVIOUS_QUESTION = "REQUEST_PREVIOUS_QUESTION";

export const SET_ANSWER_SELECTION = "SET_ANSWER_SELECTION";
export const SET_VISITED_QUESTION = "SET_VISITED_QUESTION";

export const REQUEST_COVERAGE_DATA = "REQUEST_COVERAGE_DATA";
export const RECEIVE_COVERAGE_DATA = "RECEIVE_COVERAGE_LIST";

export const REQUEST_FORMS_DOCS = "REQUEST_FORMS_DOCS";
export const RECEIVE_FORMS_DOCS = "RECEIVE_FORMS_DOCS";

export const REQUEST_CUSTOMER_INFO = "REQUEST_CUSTOMER_INFO";
export const RECEIVE_CUSTOMER_INFO = "RECEIVE_CUSTOMER_INFO";

export const REQUEST_PCP_STATUS = "REQUEST_PCP_STATUS";
export const RECEIVE_PCP_STATUS = "RECEIVE_PCP_STATUS";

export const REQUEST_PCP_UPDATE = "REQUEST_PCP_UPDATE";
export const RECEIVE_PCP_UPDATE = "RECEIVE_PCP_UPDATE";

export const REQUEST_HRA_QUESTIONS = "REQUEST_HRA_QUESTIONS";
export const RECEIVE_HRA_QUESTIONS = "RECEIVE_HRA_QUESTIONS";
export const ERROR_HRA_QUESTIONS = "ERROR_HRA_QUESTIONS";

export const REQUEST_PHYSICAL_ID_CARD = "REQUEST_PHYSICAL_ID_CARD";
export const RECEIVE_PHYSICAL_ID_CARD = "RECEIVE_PHYSICAL_ID_CARD";

export const REQUEST_DIGITAL_ID_CARD = "REQUEST_DIGITAL_ID_CARD";
export const RECEIVE_DIGITAL_ID_CARD = "RECEIVE_DIGITAL_ID_CARD";

export const REQUEST_SUBMIT_HRA_SURVEY = "REQUEST_SUBMIT_HRA_SURVEY";
// HRA
export const REQUEST_HRA_PARTIALS = "REQUEST_HRA_PARTIALS";
export const RECEIVE_HRA_PARTIALS = "RECEIVE_HRA_PARTIALS";

export const REQUEST_DD_SELECTED_MEMBER = "REQUEST_DD_SELECTED_MEMBER";

export const GET_USERNAME = "GET_USERNAME";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const RESET_MESSAGE = "RESET_MESSAGE";

export const REQUEST_CHANGE_USERNAME = "REQUEST_CHANGE_USERNAME";
export const RECEIVE_CHANGE_USERNAME = "RECEIVE_CHANGE_USERNAME";

export const REQUEST_CHANGE_PASSWORD = "REQUEST_CHANGE_PASSWORD";
export const RECEIVE_CHANGE_PASSWORD = "RECEIVE_CHANGE_PASSWORD";
export const REQUEST_CUSTOMER_DEMOGRAPHICS_INFO =
    "REQUEST_CUSTOMER_DEMOGRAPHICS_INFO";
export const RECEIVE_CUSTOMER_DEMOGRAPHICS_INFO =
    "RECEIVE_CUSTOMER_DEMOGRAPHICS_INFO";

export const REQUEST_SUBMIT_MAIL_MEMBER_ID_CARD_FORM =
    "REQUEST_SUBMIT_MAIL_MEMBER_ID_CARD_FORM";
export const RECEIVE_SUBMIT_MAIL_MEMBER_ID_CARD_FORM =
    "RECEIVE_SUBMIT_MAIL_MEMBER_ID_CARD_FORM";

// MY HEALTH (NowPow)
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const UPDATE_ICON_BY_ID = "UPDATE_ICON_BY_ID";

export const GET_CATEGORY_DETAILS = "GET_CATEGORY_DETAILS";
export const UPDATE_CATEGORY_DETAILS = "UPDATE_CATEGORY_DETAILS";

export const GET_CATEGORY_DETAILS_ALL = "GET_CATEGORY_DETAILS_ALL";
export const UPDATE_CATEGORY_DETAILS_ALL = "UPDATE_CATEGORY_DETAILS_ALL";

export const GET_CATEGORY_ICON = "GET_CATEGORY_ICON";

export const GET_IND_MAP_DETAILS = "GET_IND_MAP_DETAILS";
export const UPDATE_IND_MAP_DETAILS = "UPDATE_IND_MAP_DETAILS";

export const REQUEST_SUBMIT_CLAIM_DETAILS = "REQUEST_SUBMIT_CLAIM_DETAILS";
export const RECEIVE_SUBMIT_CLAIM_DETAILS = "RECEIVE_SUBMIT_CLAIM_DETAILS";
export const ERROR_SUBMIT_CLAIM_DETAILS = "ERROR_SUBMIT_CLAIM_DETAILS";

export const REQUEST_SUBMIT_ATTESTATION_AGREEMENT =
    "REQUEST_SUBMIT_ATTESTATION_AGREEMENT";
export const RECEIVE_SUBMIT_ATTESTATION_AGREEMENT =
    "RECEIVE_SUBMIT_ATTESTATION_AGREEMENT";
export const ERROR_SUBMIT_ATTESTATION_AGREEMENT =
    "ERROR_SUBMIT_ATTESTATION_AGREEMENT";

export const REQUEST_MAIL_MEMBER_ID_CARD_STATUS =
    "REQUEST_MAIL_MEMBER_ID_CARD_STATUS";
export const RECEIVE_MAIL_MEMBER_ID_CARD_STATUS =
    "RECEIVE_MAIL_MEMBER_ID_CARD_STATUS";

export const REQUEST_CAROUSEL_ITEMS = "REQUEST_CAROUSEL_ITEMS";
export const RECEIVE_CAROUSEL_ITEMS = "RECEIVE_CAROUSEL_ITEMS";

export const REQUEST_PCP_DETAILS = "REQUEST_PCP_DETAILS";
export const RECEIVE_PCP_DETAILS = "RECEIVE_PCP_DETAILS";

export const REQUEST_ADD_MEMBERSHIP = "REQUEST_ADD_MEMBERSHIP";
export const RECEIVE_ADD_MEMBERSHIP = "RECEIVE_ADD_MEMBERSHIP";

export const REQUEST_PREFERRED_CONTACT_INFO_SUBMIT =
    "REQUEST_PREFERRED_CONTACT_INFO_SUBMIT";
export const RECEIVE_PREFERRED_CONTACT_INFO_SUBMIT =
    "RECEIVE_PREFERRED_CONTACT_INFO_SUBMIT";

export const REQUEST_PREFERENCE_CENTER_INFO = "REQUEST_PREFERENCE_CENTER_INFO";
export const RECEIVE_PREFERENCE_CENTER_INFO = "RECEIVE_PREFERENCE_CENTER_INFO";

export const REQUEST_MFA_CODE = "REQUEST_MFA_CODE";
export const RECEIVE_MFA_CODE = "RECEIVE_MFA_CODE";
export const RESET_MFA_CODE = "RESET_MFA_CODE";

export const REQUEST_USER_MFA_CODE = "REQUEST_USER_MFA_CODE";
export const RECEIVE_USER_MFA_CODE = "RECEIVE_USER_MFA_CODE";

export const REQUEST_MFA_VERIFY = "REQUEST_MFA_VERIFY";
export const RECEIVE_MFA_VERIFY = "RECEIVE_MFA_VERIFY";
export const RESET_MFA_VERIFY = "RESET_MFA_VERIFY";

export const REQUEST_USER_MFA_VERIFY = "REQUEST_USER_MFA_VERIFY";
export const RECEIVE_USER_MFA_VERIFY = "RECEIVE_USER_MFA_VERIFY";

export const REQUEST_MFA_FACTORS = "REQUEST_MFA_FACTORS";
export const RESET_MFA_FACTORS = "RESET_MFA_FACTORS";
export const RECEIVE_MFA_FACTORS = "RECEIVE_MFA_FACTORS";

export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const RECEIVE_REGISTER = "RECEIVE_REGISTER";

export const REQUEST_CREATE_USERNAME_PASSWORD = "REQUEST_CREATE_USERNAME_PASSWORD";
export const RECEIVE_CREATE_USERNAME_PASSWORD  = "RECEIVE_CREATE_USERNAME_PASSWORD";



// Global Alerts
export const REQUEST_GLOBAL_ALERTS = "REQUEST_GLOBAL_ALERTS";
export const RECEIVE_GLOBAL_ALERTS = "RECEIVE_GLOBAL_ALERTS";

export const REQUEST_CONTACT_EMAIL_INFO = "REQUEST_CONTACT_EMAIL_INFO";
export const RECEIVE_CONTACT_EMAIL_INFO = "RECEIVE_CONTACT_EMAIL_INFO";
export const ERROR_CONTACT_EMAIL_INFO = "ERROR_CONTACT_EMAIL_INFO";

export const REQUEST_CONTACT_PHONE_INFO = "REQUEST_CONTACT_PHONE_INFO";
export const RECEIVE_CONTACT_PHONE_INFO = "RECEIVE_CONTACT_PHONE_INFO";
export const ERROR_CONTACT_PHONE_INFO = "ERROR_CONTACT_PHONE_INFO";

export const REPORT_ERROR = "REPORT_ERROR";
export const REPORT_ERROR_SUCCESS = "REPORT_ERROR_SUCCESS";

export const REQUEST_SELECT_PLAN = "REQUEST_SELECT_PLAN";
export const RECEIVE_SELECT_PLAN = "RECEIVE_SELECT_PLAN";

// OTC
export const REQUEST_OTC_CARD_STATUS = "REQUEST_OTC_CARD_STATUS";
export const RECEIVE_OTC_CARD_STATUS = "RECEIVE_OTC_CARD_STATUS";

export const RECEIVE_OTC_CARD_BALANCE = "RECEIVE_OTC_CARD_BALANCE";
export const REQUEST_OTC_CARD_BALANCE = "REQUEST_OTC_CARD_BALANCE";

export const REQUEST_OTC_PROFILE = "REQUEST_OTC_PROFILE";
export const RECEIVE_OTC_PROFILE = "RECEIVE_OTC_PROFILE";

// toggle settings left side bar
export const TOGGLE_SETTINGS_TAB_VALUE = "TOGGLE_SETTINGS_TAB_VALUE";

// Documents 
export const GET_DOCUMENT_LIST = "GET_DOCUMENT_LIST";
export const CLEAR_DOCS = "CLEAR_DOCS";
export const CLEAR_LOADING_STATUS = "CLEAR_LOADING_STATUS";
export const RECEIVE_DOCUMENT_LIST = "RECEIVE_DOCUMENT_LIST";
export const ERROR_DOCUMENT_LIST = "ERROR_DOCUMENT_LIST";

// Documents
export const GET_DOCUMENT = "GET_DOCUMENT";
export const RECEIVED_DOCUMENT_FILE = "RECEIVED_DOCUMENT_FILE";
export const DOCUMENT_ERROR = "DOCUMENT_ERROR";
export const DOCUMENT_FILE_LOADING = "DOCUMENT_FILE_LOADING";
//export const GET_DOCUMENT_LOADING = "GET_DOCUMENT_LOADING";

export const REQUEST_OTC_CLAIM_REIMBURSEMENT_DATA = "REQUEST_OTC_CLAIM_REIMBURSEMENT_DATA";
export const RECEIVE_OTC_CLAIM_REIMBURSEMENT_DATA = "RECEIVE_OTC_CLAIM_REIMBURSEMENT_DATA";
export const ERROR_OTC_CLAIM_REIMBURSEMENT_DATA = "ERROR_OTC_CLAIM_REIMBURSEMENT_DATA";

// FORGOT USERNAME
export const REQUEST_FORGOT_USERNAME = "REQUEST_FORGOT_USERNAME";
export const RECEIVE_FORGOT_USERNAME = "RECEIVE_FORGOT_USERNAME";
export const RESET_FORGOT_USERNAME = "RESET_FORGOT_USERNAME"; 

export const REQUEST_FORGOT_PASSWORD = "REQUEST_FORGOT_PASSWORD";
export const RECEIVE_FORGOT_PASSWORD = "RECEIVE_FORGOT_PASSWORD";
export const RESET_FORGOT_PASSWORD = "RESET_FORGOT_PASSWORD"; 

export const REQUEST_SET_PASSWORD = "REQUEST_SET_PASSWORD";
export const RECEIVE_SET_PASSWORD = "RECEIVE_SET_PASSWORD";
export const RESET_SET_PASSWORD = "RESET_SET_PASSWORD";

export const REQUEST_VERIFY_ADDRESS = "REQUEST_VERIFY_ADDRESS";
export const RECEIVE_VERIFY_ADDRESS = "RECEIVE_VERIFY_ADDRESS";
export const RESET_VERIFY_ADDRESS = "RESET_VERIFY_ADDRESS";

// Reset Redux
export const REQUEST_RESET_STATE = "REQUEST_RESET_REDUX";
export const RESET_REGISTER = "RESET_REGISTER";
export const REQUEST_RESET_PCP_DETAILS = "REQUEST_RESET_PCP_DETAILS";

export const UPDATE_CUSTOMER_INFO = "UPDATE_CUSTOMER_INFO";

// PCP Household
export const REQUEST_PCP_HOUSEHOLD = "REQUEST_PCP_HOUSEHOLD";
export const RECEIVE_PCP_HOUSEHOLD = "RECEIVE_PCP_HOUSEHOLD";

// FormsAndDocument 
export const REQUEST_CC_FORMS_DOCS = "REQUEST_CC_FORMS_DOCS";
export const RECEIVE_CC_FORMS_DOCS = "RECEIVE_CC_FORMS_DOCS";
