export const StateLabelValues = [
  { label: "Alabama", value: { label: "Alabama", code: "AL" } },
  { label: "Alaska", value: { label: "Alaska", code: "AK" } },
  { label: "American Samoa", value: { label: "American Samoa", code: "AS" } },
  { label: "Arizona", value: { label: "Arizona", code: "AZ" } },
  { label: "Arkansas", value: { label: "Arkansas", code: "AR" } },
  { label: "California", value: { label: "California", code: "CA" } },
  { label: "Colorado", value: { label: "Colorado", code: "CO" } },
  { label: "Connecticut", value: { label: "Connecticut", code: "CT" } },
  { label: "Delaware", value: { label: "Delaware", code: "DE" } },
  {
    label: "District of Columbia",
    value: { label: "District of Columbia", code: "DC" },
  },
  { label: "Florida", value: { label: "Florida", code: "FL" } },
  { label: "Georgia", value: { label: "Georgia", code: "GA" } },
  { label: "Guam", value: { label: "Guam", code: "GU" } },
  { label: "Hawaii", value: { label: "Hawaii", code: "HI" } },
  { label: "Idaho", value: { label: "Idaho", code: "ID" } },
  { label: "Illinois", value: { label: "Illinois", code: "IL" } },
  { label: "Indiana", value: { label: "Indiana", code: "IN" } },
  { label: "Iowa", value: { label: "Iowa", code: "IA" } },
  { label: "Kansas", value: { label: "Kansas", code: "KS" } },
  { label: "Kentucky", value: { label: "Kentucky", code: "KY" } },
  { label: "Louisiana", value: { label: "Louisiana", code: "LA" } },
  { label: "Maine", value: { label: "Maine", code: "ME" } },
  { label: "Maryland", value: { label: "Maryland", code: "MD" } },
  { label: "Massachusetts", value: { label: "Massachusetts", code: "MA" } },
  { label: "Michigan", value: { label: "Michigan", code: "MI" } },
  { label: "Minnesota", value: { label: "Minnesota", code: "MN" } },
  { label: "Mississippi", value: { label: "Mississippi", code: "MS" } },
  { label: "Missouri", value: { label: "Missouri", code: "MO" } },
  { label: "Montana", value: { label: "Montana", code: "MT" } },
  { label: "Nebraska", value: { label: "Nebraska", code: "NE" } },
  { label: "Nevada", value: { label: "Nevada", code: "NV" } },
  { label: "New Hampshire", value: { label: "New Hampshire", code: "NH" } },
  { label: "New Jersey", value: { label: "New Jersey", code: "NJ" } },
  { label: "New Mexico", value: { label: "New Mexico", code: "NM" } },
  { label: "New York", value: { label: "New York", code: "NY" } },
  { label: "North Carolina", value: { label: "North Carolina", code: "NC" } },
  { label: "North Dakota", value: { label: "North Dakota", code: "ND" } },
  { label: "Ohio", value: { label: "Ohio", code: "OH" } },
  { label: "Oklahoma", value: { label: "Oklahoma", code: "OK" } },
  { label: "Oregon", value: { label: "Oregon", code: "OR" } },
  { label: "Pennsylvania", value: { label: "Pennsylvania", code: "PA" } },
  { label: "Puerto Rico", value: { label: "Puerto Rico", code: "PR" } },
  { label: "Rhode Island", value: { label: "Rhode Island", code: "RI" } },
  { label: "South Carolina", value: { label: "South Carolina", code: "SC" } },
  { label: "South Dakota", value: { label: "South Dakota", code: "SD" } },
  { label: "Tennessee", value: { label: "Tennessee", code: "TN" } },
  { label: "Texas", value: { label: "Texas", code: "TX" } },
  { label: "Utah", value: { label: "Utah", code: "UT" } },
  { label: "Vermont", value: { label: "Vermont", code: "VT" } },
  { label: "Virgin Islands", value: { label: "Virgin Islands", code: "VI" } },
  { label: "Virginia", value: { label: "Virginia", code: "VA" } },
  { label: "Washington", value: { label: "Washington", code: "WA" } },
  { label: "West Virginia", value: { label: "West Virginia", code: "WV" } },
  { label: "Wisconsin", value: { label: "Wisconsin", code: "WI" } },
  { label: "Wyoming", value: { label: "Wyoming", code: "WY" } },
];

export const ClaimLabelValues = [
  {
    label: "Provider Claim/Bill - Emergency Care",
    value: "Provider Claim/Bill - Emergency Care",
  },
  {
    label: "Provider Claim/Bill - Out of Network Care",
    value: "Provider Claim/Bill - Out of Network Care",
  },
  {
    label: "Other - Attach Receipt and Description",
    value: "Other - Attach Receipt and Description",
  },
  {
    label: "Out of Country - Urgent or Emergency Care",
    value: "Out of Country - Urgent or Emergency Care",
  },
];

export const PhoneTypeValues = [{ label: "Mobile", value: "Mobile" }];
